"""CVM open-data **Fundos de Investimento Imobiliário** readers (`FII/`).

Mirrors the `dados.cvm.gov.br/dados/FII/` portal branch — one sibling among the portal's other
roots (`FI/`, `FIDC/`, `AUDITOR/`, …), each of which gets its own sub-package here as it is
implemented. Under `FII/` live only the document dumps
(:mod:`filings_cvm.ingestion.fii.doc`) — the portal publishes no `FII/CAD`. Every reader, plus its
META reader, is re-exported flat from `filings_cvm.ingestion`.
"""

from filings_cvm.ingestion.fii.doc import (
	DfinFiiReader,
	InfAnualFiiAtivoAdquiridoReader,
	InfAnualFiiAtivoTransacaoReader,
	InfAnualFiiAtivoValorContabilReader,
	InfAnualFiiComplementoReader,
	InfAnualFiiDiretorResponsavelReader,
	InfAnualFiiDistribuicaoCotistasReader,
	InfAnualFiiExperienciaProfissionalReader,
	InfAnualFiiGeralReader,
	InfAnualFiiPrestadorServicoReader,
	InfAnualFiiProcessoReader,
	InfAnualFiiProcessoSemelhanteReader,
	InfAnualFiiRepresentanteCotistaReader,
	InfMensalFiiAtivoPassivoReader,
	InfMensalFiiComplementoReader,
	InfMensalFiiGeralReader,
	InfTrimestralFiiAlienacaoImovelReader,
	InfTrimestralFiiAlienacaoTerrenoReader,
	InfTrimestralFiiAquisicaoImovelReader,
	InfTrimestralFiiAquisicaoTerrenoReader,
	InfTrimestralFiiAtivoGarantiaRentabilidadeReader,
	InfTrimestralFiiAtivoReader,
	InfTrimestralFiiComplementoReader,
	InfTrimestralFiiDireitoReader,
	InfTrimestralFiiGeralReader,
	InfTrimestralFiiImovelDesempenhoReader,
	InfTrimestralFiiImovelReader,
	InfTrimestralFiiImovelRendaAcabadoContratoReader,
	InfTrimestralFiiImovelRendaAcabadoInquilinoReader,
	InfTrimestralFiiRentabilidadeEfetivaReader,
	InfTrimestralFiiResultadoContabilFinanceiroReader,
	InfTrimestralFiiTerrenoReader,
	MetaDfinFiiReader,
	MetaInfAnualFiiReader,
	MetaInfMensalFiiReader,
	MetaInfTrimestralFiiReader,
)


__all__ = [
	"DfinFiiReader",
	"InfAnualFiiAtivoAdquiridoReader",
	"InfAnualFiiAtivoTransacaoReader",
	"InfAnualFiiAtivoValorContabilReader",
	"InfAnualFiiComplementoReader",
	"InfAnualFiiDiretorResponsavelReader",
	"InfAnualFiiDistribuicaoCotistasReader",
	"InfAnualFiiExperienciaProfissionalReader",
	"InfAnualFiiGeralReader",
	"InfAnualFiiPrestadorServicoReader",
	"InfAnualFiiProcessoReader",
	"InfAnualFiiProcessoSemelhanteReader",
	"InfAnualFiiRepresentanteCotistaReader",
	"InfMensalFiiAtivoPassivoReader",
	"InfMensalFiiComplementoReader",
	"InfMensalFiiGeralReader",
	"InfTrimestralFiiAlienacaoImovelReader",
	"InfTrimestralFiiAlienacaoTerrenoReader",
	"InfTrimestralFiiAquisicaoImovelReader",
	"InfTrimestralFiiAquisicaoTerrenoReader",
	"InfTrimestralFiiAtivoGarantiaRentabilidadeReader",
	"InfTrimestralFiiAtivoReader",
	"InfTrimestralFiiComplementoReader",
	"InfTrimestralFiiDireitoReader",
	"InfTrimestralFiiGeralReader",
	"InfTrimestralFiiImovelDesempenhoReader",
	"InfTrimestralFiiImovelReader",
	"InfTrimestralFiiImovelRendaAcabadoContratoReader",
	"InfTrimestralFiiImovelRendaAcabadoInquilinoReader",
	"InfTrimestralFiiRentabilidadeEfetivaReader",
	"InfTrimestralFiiResultadoContabilFinanceiroReader",
	"InfTrimestralFiiTerrenoReader",
	"MetaDfinFiiReader",
	"MetaInfAnualFiiReader",
	"MetaInfMensalFiiReader",
	"MetaInfTrimestralFiiReader",
]
